---
title: "title"
author: Name
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
   theme: flatly # default, cerulean, journal, flatly, darkly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, and yeti
   highlight: tango # default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, breezedark, and textmate
   smart: true
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scroll: false
   numbers_sections: true
   fig_width: 7
   fig_height: 6
   fig_caption: true
   df_print: paged
   code_folding: hide

runtime: shiny  

#bibliography: biobliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1234)
library(knitr)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(purrr)
freqsByYear <- list(LG1 = structure(list(YEAR = c(1L, 1L, 1L, 1L, 2L, 2L, 2L
), LG1 = c(2L, 3L, 4L, 5L, 3L, 4L, 5L), n = c(1L, 26L, 64L, 25L, 
13L, 33L, 36L)), class = "data.frame", row.names = c(NA, -7L)), 
    AA1 = structure(list(YEAR = c(1L, 1L, 1L, 1L, 2L, 2L, 2L, 
    2L, 2L), AA1 = c(1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 5L), n = c(31L, 
    44L, 30L, 11L, 28L, 30L, 15L, 8L, 1L)), class = "data.frame", row.names = c(NA, 
    -9L)), FNB1 = structure(list(YEAR = c(1L, 1L, 1L, 1L, 2L, 
    2L, 2L, 2L, 2L), FNB1 = c(2L, 3L, 4L, 5L, 1L, 2L, 3L, 4L, 
    5L), n = c(16L, 12L, 68L, 20L, 1L, 2L, 9L, 35L, 35L)), class = "data.frame", row.names = c(NA, 
    -9L)), RE1 = structure(list(YEAR = c(1L, 1L, 1L, 1L, 1L, 
    2L, 2L, 2L, 2L, 2L), RE1 = c(1L, 2L, 3L, 4L, 5L, 1L, 2L, 
    3L, 4L, 5L), n = c(24L, 58L, 26L, 7L, 1L, 24L, 29L, 23L, 
    5L, 1L)), class = "data.frame", row.names = c(NA, -10L)))
```


```{r method1}

selectInput("selector",label = "Selector",
      choices = names(freqsByYear),
      selected = 1)

renderPlot(freqsByYear %>% 
  pluck(., input$selector) %>% 
  ggplot(aes(x = !!sym(input$selector), y = n, fill = n)) +
  geom_col() +
  facet_wrap(~YEAR))

```

## My Header {.tabset .tabset-dropdown}

